# Generated by Django 4.1.5 on 2023-01-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50)),
                ('car_year', models.PositiveIntegerField()),
                ('cost', models.IntegerField()),
                ('mileage', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car_bnb_app.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car_bnb_app.person')),
            ],
            options={
                'db_table': 'rent',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='car_bnb_app.person'),
        ),
    ]
