# Generated by Django 4.1.5 on 2023-02-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_bnb_app', '0002_alter_rent_end_date_alter_rent_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(through='car_bnb_app.Rent', to='car_bnb_app.person'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='car_owner', to='car_bnb_app.person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
