# Generated by Django 4.1.5 on 2023-02-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_bnb_app', '0004_car_plate_number_alter_car_renters'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(blank=True, related_name='rented_cars', through='car_bnb_app.Rent', to='car_bnb_app.person'),
        ),
    ]
